services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
      network: host
    container_name: fastapi_local
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env          # COMMON settings
    network_mode: "host"
    depends_on:
      - postgres
      - redis
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  postgres:
    image: postgres:16-alpine
    container_name: postgres_local
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ai_agent_playstore
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    network_mode: "host"

  redis:
    image: redis:7-alpine
    container_name: redis_local
    ports:
      - "6379:6379"
    command: [ "redis-server", "--save", "", "--appendonly", "no" ]
    network_mode: "host"

volumes:
  pgdata: